### ISSUE TITLE
Hi, there, I wonder this repo still works?

### ISSUE THREAD

**Issue by 2018-freecoder** [GoREACT/widgets-js-api#6]
Hi, there
I found this example use goreact api, such as `https://goreact.com/widgets/v2/auth` or `https://goreact.com/widgets/v2/templates/record`, is the api endpoint still available?
also I found in wiki, we need prepare `user_id` and `api_key` when we authorize to GoReact, however I didn't find a way to get the user_id or api_key, where should I find it?

many thanks

**Comment by erikdonohoo** [comment]
Hey there @2018-freecoder. This method of integrating with GoRoreact is no longer supported. The best way to integrate with us today is by using the LTI standard used by most LMS’s like Canvas and Blackboard. You can even build a custom LTI integration. Check out our help articles on https://help.goreact.com and you can reach out to our support team there if you have other questions.

**Comment by 2018-freecoder** [comment]
@erikdonohoo thanks, I will take a look
